### ISSUE TITLE
"⚠️ We ask that you tag your PR with the GoR label!"

### ISSUE THREAD

**Issue by moul** [gnolang/game-of-realms#4]
It's outlined in the README, but I'm uncertain how individuals can proceed without being part of the organization. Can we clarify?

**Comment by roethke** [comment]
This is a good point. It was asked to be included though perhaps Github label assignment permissions were not well understood with this request. We will think about an alternative way of identifying GoR contributions.

**Comment by michelleellen** [comment]
Is it possible to assign an open policy for the GoR repo, (not merge rights...etc) so anyone can select from the label selection? Especially if we want it to be contribution based that would be a good iniatitive? 

I.e once you have opened a PR or issue you've initiated a status as contributor and therefore you have a level one ability ...i.e adding a label like GoR but also documentation, or Evaluation DAO...etc.

**Comment by roethke** [comment]
@michelleellen I was discussing something similar with @MichaelFrazzy, though I think labels should be assignable **only by the team itself** (or whoever is stewarding our repos) to avoid a lot of issues going forward (eg, mischievous actors wrecking havoc on our organization efforts).

As a middle-ground idea I was thinking we could have the contributors self-attest within the README of their PR what label they believe it should be given based on the options we provide, though ultimately we should be ones to set the labels.

**Contributors handle their READMEs + code; our team/a DAO should manage everything else (including repository management).**

Perhaps the quality of a contributor's README could also afford to be considered by the Evaluation DAO since this is the first thing we will see when introduced to the PR.

As an example, in hopes of ensuring greater quality of submission, we could request that PR READMEs follow a strict structure (like Github issue templates) which would have a section for proposed labels within that, for example, Eval DAO/automation would be able to check for first then a team member could manually assign any additional labels thereafter, if necessary.

**Comment by michelleellen** [comment]
Closing this for now
